import os

POSTGRES_DB = os.getenv('POSTGRES_DB', 'adv')
POSTGRES_HOST = os.getenv('POSTGRES_HOST', 'localhost')
POSTGRES_PORT = os.getenv('POSTGRES_PORT', '5433')
POSTGRES_USER = os.getenv('POSTGRES_USER', 'adv')
POSTGRES_PASSWORD = os.getenv('POSTGRES_PASSWORD', 'adv_pass')

PG_DSN = f'postgresql+asyncpg://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}'

TOKEN_TTL_SEC  = 60 * 60 * 48